// @vitest-environment happy-dom

import { describe, expect, test } from "vitest";
import { mountChatSurface } from "./chatSurface";
import type { ChatUiProjection } from "../../chat/chatUiProjection";

describe("rebuilt chat surface", () => {
  test("renders projection-driven two-column shell without legacy thread ownership", () => {
    const host = document.createElement("section");

    const mounted = mountChatSurface(host, {
      projection: fixtureProjection(),
    });

    expect(host.getAttribute("data-chat-surface")).toBe("rebuild-chat-agent-surface");
    expect(host.querySelector("[data-chat-region='session-list']")).not.toBeNull();
    expect(host.querySelector("[data-chat-region='chat-detail']")).not.toBeNull();
    expect(host.querySelector("[data-chat-region='session-list']")?.textContent).toContain("Investigate IAM certificate");
    expect(host.querySelector("[data-session-primary-badge='waiting_approval']")?.textContent).toBe("Waiting approval");
    expect(host.querySelector("[data-chat-region='chat-header']")?.textContent).toContain("Investigate IAM certificate");
    expect(host.querySelector("[data-chat-region='chat-header']")?.textContent).toContain("Agent · rust");
    expect(host.querySelector("[data-chat-region='conversation']")?.textContent).toContain("Execution process · 2 tools");
    expect(host.querySelector("[data-chat-region='thinking-summary']")?.textContent).toContain("Looking at workspace docs.");
    expect(host.querySelector("[data-chat-region='tool-row']")?.textContent).toContain("workspace.read_file");
    expect(host.querySelector("[data-chat-region='conversation']")?.textContent).not.toContain("{\"path\":\"README.md\"}");
    expect(host.querySelector("[data-chat-region='conversation']")?.textContent).not.toContain("{\"path\":\"notes.md\"}");
    expect(host.querySelector("[data-chat-region='legacy-conversation-thread']")).toBeNull();

    mounted.unmount();
    expect(host.textContent).toBe("");
  });

  test("renders tool detail in a right overlay drawer from projection state", () => {
    const host = document.createElement("section");
    const projection = fixtureProjection();
    projection.detailPanel = {
      kind: "tool",
      open: true,
      presentation: "drawer",
      targetId: "tool-1",
    };

    mountChatSurface(host, { projection });

    const drawer = host.querySelector("[data-chat-region='detail-surface']");
    expect(drawer?.getAttribute("data-detail-presentation")).toBe("drawer");
    expect(drawer?.getAttribute("data-detail-kind")).toBe("tool");
    expect(drawer?.textContent).toContain("workspace.read_file");
    expect(drawer?.textContent).toContain("README contents");
    expect(drawer?.querySelector("[data-tool-detail-section='full-args']")?.getAttribute("open")).toBeNull();
    expect(drawer?.querySelector("[data-tool-detail-section='full-result']")?.getAttribute("open")).toBeNull();
    expect(drawer?.querySelector("[data-tool-detail-copy='full-args']")).not.toBeNull();
    expect(drawer?.querySelector("[data-tool-detail-copy='full-result']")).not.toBeNull();
  });

  test("opens and closes tool detail from a tool row click", () => {
    const host = document.createElement("section");
    const logEvents: unknown[] = [];
    host.addEventListener("desktop-chat-surface-log", (event) => {
      logEvents.push((event as CustomEvent).detail);
    });

    mountChatSurface(host, { projection: fixtureProjection() });

    expect(host.querySelector("[data-chat-region='detail-surface']")).toBeNull();

    host.querySelector<HTMLButtonElement>("[data-tool-call-id='tool-1']")?.click();

    const detail = host.querySelector("[data-chat-region='detail-surface']");
    expect(detail?.getAttribute("data-detail-kind")).toBe("tool");
    expect(detail?.textContent).toContain("workspace.read_file");

    host.querySelector<HTMLButtonElement>("[data-detail-action='close']")?.click();

    expect(host.querySelector("[data-chat-region='detail-surface']")).toBeNull();
    expect(logEvents).toEqual([
      {
        action: "detail.open",
        panel: {
          kind: "tool",
          open: true,
          presentation: "drawer",
          targetId: "tool-1",
        },
      },
      {
        action: "detail.close",
        panel: {
          kind: "none",
          open: false,
          presentation: "drawer",
        },
      },
    ]);
  });

  test("renders fullscreen artifact and error detail from shared detail model", () => {
    const artifactHost = document.createElement("section");
    const artifactProjection = fixtureProjection();
    artifactProjection.detailPanel = {
      kind: "artifact",
      open: true,
      presentation: "fullscreen",
      targetId: "artifact-1",
    };
    artifactProjection.artifacts = [{
      id: "artifact-1",
      kind: "markdown",
      title: "Implementation report",
      preview: "Report preview",
      metadataSummary: "Generated by workspace.write_file",
      sourceTurnId: "m-assistant",
      openLabel: "Open file",
    }];

    mountChatSurface(artifactHost, { projection: artifactProjection });
    const artifactDetail = artifactHost.querySelector("[data-chat-region='detail-surface']");
    expect(artifactDetail?.getAttribute("data-detail-presentation")).toBe("fullscreen");
    expect(artifactDetail?.getAttribute("data-detail-kind")).toBe("artifact");
    expect(artifactDetail?.textContent).toContain("Implementation report");
    expect(artifactDetail?.textContent).toContain("Report preview");
    expect(artifactDetail?.querySelector("[data-detail-action='close']")).not.toBeNull();
    expect(artifactDetail?.querySelector("[data-artifact-action='future-management']")).not.toBeNull();

    const errorHost = document.createElement("section");
    const errorProjection = fixtureProjection();
    errorProjection.detailPanel = {
      kind: "error",
      open: true,
      presentation: "drawer",
      targetId: "error-1",
    };
    errorProjection.errors = [{
      id: "error-1",
      message: "Command failed",
      raw: "stack trace",
      relatedTurnId: "m-assistant",
      relatedToolId: "tool-1",
    }];

    mountChatSurface(errorHost, { projection: errorProjection });
    const errorDetail = errorHost.querySelector("[data-chat-region='detail-surface']");
    expect(errorDetail?.getAttribute("data-detail-kind")).toBe("error");
    expect(errorDetail?.textContent).toContain("Command failed");
    expect(errorDetail?.querySelector("[data-error-detail-section='raw']")?.getAttribute("open")).toBeNull();
    expect(errorDetail?.querySelector("[data-error-detail-copy='raw']")).not.toBeNull();
  });

  test("renders live subagent strip and partial transcript as read-only detail", () => {
    const host = document.createElement("section");
    const projection = fixtureProjection();
    projection.liveSubagents = [{
      id: "delegate-1",
      sessionKey: "websocket:chat-1",
      name: "Researcher",
      task: "Check docs",
      status: "user_intervened_unsynced",
      latestActivity: "User replied directly",
      capabilities: ["partial_transcript", "can_forward"],
      transcript: {
        id: "delegate-1",
        sessionKey: "websocket:chat-1",
        capability: "partial_transcript",
        messages: [{
          id: "sub-msg-1",
          role: "assistant",
          content: "I found a partial result.",
          timestamp: "2026-07-01T10:04:00Z",
        }],
        toolSummaries: [{
          id: "tool-sub",
          name: "workspace.read_file",
          status: "completed",
          preview: "read docs",
        }],
      },
    }];
    projection.detailPanel = {
      kind: "subagent",
      open: true,
      presentation: "drawer",
      targetId: "delegate-1",
    };

    mountChatSurface(host, { projection });

    const strip = host.querySelector("[data-chat-region='subagent-strip']");
    expect(strip?.textContent).toContain("Researcher");
    expect(strip?.textContent).toContain("User replied directly");
    expect(strip?.querySelector("[data-subagent-status='user_intervened_unsynced']")).not.toBeNull();

    const detail = host.querySelector("[data-chat-region='detail-surface']");
    expect(detail?.getAttribute("data-detail-kind")).toBe("subagent");
    expect(detail?.textContent).toContain("partial transcript");
    expect(detail?.textContent).toContain("I found a partial result.");
    expect(detail?.textContent).toContain("not a complete private thread");
    expect(detail?.querySelector("[data-subagent-input='message']")).toBeNull();
    expect(detail?.querySelector("[data-subagent-action='forward']")).not.toBeNull();
  });

  test("opens subagent detail from the active goals strip", () => {
    const host = document.createElement("section");
    const projection = fixtureProjection();
    projection.liveSubagents = [{
      id: "delegate-click",
      sessionKey: "websocket:chat-1",
      name: "Researcher",
      task: "Check docs",
      status: "waiting_main_agent",
      latestActivity: "Waiting for main agent",
      capabilities: ["partial_transcript", "can_forward"],
      transcript: {
        id: "delegate-click",
        sessionKey: "websocket:chat-1",
        capability: "partial_transcript",
        messages: [{ id: "sub-msg-click", role: "assistant", content: "Partial answer." }],
        toolSummaries: [],
      },
    }];

    mountChatSurface(host, { projection });

    host.querySelector<HTMLButtonElement>("[data-subagent-id='delegate-click']")?.click();

    const detail = host.querySelector("[data-chat-region='detail-surface']");
    expect(detail?.getAttribute("data-detail-kind")).toBe("subagent");
    expect(detail?.textContent).toContain("Researcher");
    expect(detail?.textContent).toContain("Partial answer.");
  });

  test("enables subagent input only for full sendable transcript", () => {
    const host = document.createElement("section");
    const projection = fixtureProjection();
    projection.liveSubagents = [{
      id: "delegate-2",
      sessionKey: "websocket:chat-1",
      name: "Reviewer",
      task: "Review implementation",
      status: "waiting_user",
      latestActivity: "Needs product choice",
      capabilities: ["full_transcript", "can_send_message", "can_forward"],
      transcript: {
        id: "delegate-2",
        sessionKey: "websocket:chat-1",
        capability: "full_transcript",
        messages: [{
          id: "sub-msg-2",
          role: "assistant",
          content: "Which tradeoff should I choose?",
        }],
        toolSummaries: [],
      },
    }];
    projection.detailPanel = {
      kind: "subagent",
      open: true,
      presentation: "drawer",
      targetId: "delegate-2",
    };

    mountChatSurface(host, { projection });

    expect(host.querySelector("[data-subagent-input='message']")).not.toBeNull();
    expect(host.querySelector("[data-chat-region='detail-surface']")?.textContent).toContain("Messages are sent only to this subagent");
  });

  test("forwards selected subagent messages into the main composer draft", () => {
    const host = document.createElement("section");
    const projection = fixtureProjection();
    projection.liveSubagents = [{
      id: "delegate-forward",
      sessionKey: "websocket:chat-1",
      name: "Researcher",
      task: "Review implementation",
      status: "waiting_user",
      latestActivity: "Needs product choice",
      capabilities: ["full_transcript", "can_send_message", "can_forward"],
      transcript: {
        id: "delegate-forward",
        sessionKey: "websocket:chat-1",
        capability: "full_transcript",
        messages: [
          { id: "sub-msg-user", role: "user", content: "Prefer lower risk." },
          { id: "sub-msg-assistant", role: "assistant", content: "Use read-only analysis." },
        ],
        toolSummaries: [],
      },
    }];
    projection.detailPanel = {
      kind: "subagent",
      open: true,
      presentation: "drawer",
      targetId: "delegate-forward",
    };

    mountChatSurface(host, { projection });

    const composerInput = host.querySelector<HTMLTextAreaElement>("[data-chat-composer-input]");
    composerInput!.value = "Continue from this context.";
    composerInput!.dispatchEvent(new Event("input", { bubbles: true }));
    host.querySelector<HTMLInputElement>("[data-subagent-message-select='sub-msg-assistant']")!.checked = true;
    host.querySelector<HTMLButtonElement>("[data-subagent-action='forward']")?.click();

    const draft = host.querySelector<HTMLTextAreaElement>("[data-chat-composer-input]")?.value ?? "";
    expect(draft).toContain("Continue from this context.");
    expect(draft).toContain("Forwarded from subagent: Researcher");
    expect(draft).toContain("assistant: Use read-only analysis.");
    expect(draft).not.toContain("Prefer lower risk.");
  });

  test("preserves subagent message drafts by subagent panel", () => {
    const host = document.createElement("section");
    const projection = fixtureProjection();
    projection.liveSubagents = [
      {
        id: "delegate-a",
        sessionKey: "websocket:chat-1",
        name: "Researcher A",
        task: "Review A",
        status: "waiting_user",
        latestActivity: "Needs product choice",
        capabilities: ["full_transcript", "can_send_message"],
        transcript: {
          id: "delegate-a",
          sessionKey: "websocket:chat-1",
          capability: "full_transcript",
          messages: [],
          toolSummaries: [],
        },
      },
      {
        id: "delegate-b",
        sessionKey: "websocket:chat-1",
        name: "Researcher B",
        task: "Review B",
        status: "waiting_user",
        latestActivity: "Needs product choice",
        capabilities: ["full_transcript", "can_send_message"],
        transcript: {
          id: "delegate-b",
          sessionKey: "websocket:chat-1",
          capability: "full_transcript",
          messages: [],
          toolSummaries: [],
        },
      },
    ];
    projection.detailPanel = {
      kind: "subagent",
      open: true,
      presentation: "drawer",
      targetId: "delegate-a",
    };
    const mounted = mountChatSurface(host, { projection });

    const firstInput = host.querySelector<HTMLTextAreaElement>("[data-subagent-input='message']");
    firstInput!.value = "Draft for A";
    firstInput!.dispatchEvent(new Event("input", { bubbles: true }));

    mounted.update({
      projection: {
        ...projection,
        detailPanel: { ...projection.detailPanel, targetId: "delegate-b" },
      },
    });
    expect(host.querySelector<HTMLTextAreaElement>("[data-subagent-input='message']")?.value).toBe("");

    mounted.update({ projection });
    expect(host.querySelector<HTMLTextAreaElement>("[data-subagent-input='message']")?.value).toBe("Draft for A");
  });

  test("requires first-send confirmation for waiting-main-agent subagent messages", () => {
    const host = document.createElement("section");
    const projection = fixtureProjection();
    projection.liveSubagents = [{
      id: "delegate-waiting-main",
      sessionKey: "websocket:chat-1",
      name: "Implementer",
      task: "Wait for main agent context",
      status: "waiting_main_agent",
      latestActivity: "Waiting for main agent",
      capabilities: ["full_transcript", "can_send_message", "can_forward"],
      transcript: {
        id: "delegate-waiting-main",
        sessionKey: "websocket:chat-1",
        capability: "full_transcript",
        messages: [],
        toolSummaries: [],
      },
    }];
    projection.detailPanel = {
      kind: "subagent",
      open: true,
      presentation: "drawer",
      targetId: "delegate-waiting-main",
    };

    mountChatSurface(host, { projection });

    const confirmation = host.querySelector("[data-subagent-action='first-send-confirm']");
    expect(confirmation).not.toBeNull();
    expect(confirmation?.textContent).toContain("Confirm first direct message");
    expect(host.querySelector("[data-subagent-input='message']")?.getAttribute("data-requires-confirmation")).toBe("true");
  });

  test("keeps completed subagent details read-only", () => {
    const host = document.createElement("section");
    const projection = fixtureProjection();
    projection.liveSubagents = [{
      id: "delegate-completed",
      sessionKey: "websocket:chat-1",
      name: "Researcher",
      task: "Completed research",
      status: "completed",
      latestActivity: "Finished",
      capabilities: ["full_transcript", "can_send_message", "can_forward"],
      transcript: {
        id: "delegate-completed",
        sessionKey: "websocket:chat-1",
        capability: "full_transcript",
        messages: [{ id: "done-1", role: "assistant", content: "Done." }],
        toolSummaries: [],
      },
    }];
    projection.detailPanel = {
      kind: "subagent",
      open: true,
      presentation: "drawer",
      targetId: "delegate-completed",
    };

    mountChatSurface(host, { projection });

    expect(host.querySelector("[data-subagent-input='message']")).toBeNull();
    expect(host.querySelector("[data-chat-region='detail-surface']")?.textContent).toContain("This subagent is closed");
  });

  test("renders inline approval card and queued input near composer", () => {
    const host = document.createElement("section");
    const approvalActions: unknown[] = [];
    host.addEventListener("desktop-tool-approval-action", (event) => {
      approvalActions.push((event as CustomEvent).detail);
    });
    const projection = fixtureProjection();
    projection.approvals = [{
      id: "approval-1",
      sessionKey: "websocket:chat-1",
      toolName: "workspace.write_file",
      status: "pending",
      scopeKey: "filesystem.write:workspace",
      scopeLabel: "Allow workspace writes for this session",
      prompt: "Allow writing notes.md?",
      choices: ["allow_once", "allow_session", "deny"],
    }];
    projection.queuedInputs = [{
      id: "queued-1",
      mode: "queued",
      content: "Summarize after this.",
      createdAt: "2026-07-01T10:20:00Z",
      status: "queued",
    }];

    mountChatSurface(host, { projection });

    const approval = host.querySelector("[data-chat-region='approval-card']");
    expect(approval?.textContent).toContain("Allow writing notes.md?");
    expect(approval?.textContent).toContain("Allow once");
    expect(approval?.textContent).toContain("Allow workspace writes for this session");
    expect(host.querySelector("[data-composer-mode='approval_guidance']")?.textContent).toContain("发送文字将拒绝此请求");

    host.querySelector<HTMLButtonElement>("[data-desktop-approval-action='approveOnce']")?.click();
    host.querySelector<HTMLButtonElement>("[data-desktop-approval-action='approveSession']")?.click();
    host.querySelector<HTMLButtonElement>("[data-desktop-approval-action='deny']")?.click();
    expect(approvalActions).toEqual([
      {
        action: "approveOnce",
        approvalId: "approval-1",
        sessionKey: "websocket:chat-1",
        toolName: "workspace.write_file",
      },
      {
        action: "approveSession",
        approvalId: "approval-1",
        sessionKey: "websocket:chat-1",
        toolName: "workspace.write_file",
      },
      {
        action: "deny",
        approvalId: "approval-1",
        sessionKey: "websocket:chat-1",
        toolName: "workspace.write_file",
      },
    ]);

    const queue = host.querySelector("[data-chat-region='queued-inputs']");
    expect(queue?.textContent).toContain("Summarize after this.");
    expect(queue?.querySelector("[data-queued-input-action='delete']")).not.toBeNull();
    expect(queue?.querySelector("[data-queued-input-action='guide']")).toBeNull();
  });

  test("submits normal composer text as a main chat message event", () => {
    const host = document.createElement("section");
    const submissions: unknown[] = [];
    host.addEventListener("desktop-chat-message-submit", (event) => {
      submissions.push((event as CustomEvent).detail);
    });

    mountChatSurface(host, { projection: fixtureProjection() });

    const input = host.querySelector<HTMLTextAreaElement>("[data-chat-composer-input]");
    input!.value = "Continue with the local docs.";
    host.querySelector<HTMLButtonElement>("[data-chat-composer-action='send']")?.click();

    expect(submissions).toEqual([{ content: "Continue with the local docs." }]);
    expect(input?.value).toBe("");
  });

  test("preserves composer drafts per active session across surface updates", () => {
    const host = document.createElement("section");
    const mounted = mountChatSurface(host, { projection: fixtureProjection() });
    const firstInput = host.querySelector<HTMLTextAreaElement>("[data-chat-composer-input]");
    firstInput!.value = "Draft for chat one";
    firstInput!.dispatchEvent(new Event("input", { bubbles: true }));

    mounted.update({ projection: fixtureProjection() });

    expect(host.querySelector<HTMLTextAreaElement>("[data-chat-composer-input]")?.value).toBe("Draft for chat one");

    const secondProjection = fixtureProjection();
    secondProjection.activeSessionKey = "websocket:chat-2";
    secondProjection.sessions = [
      { ...secondProjection.sessions[0], isActive: false },
      {
        key: "websocket:chat-2",
        chatId: "chat-2",
        title: "Second chat",
        createdAt: "2026-07-01T11:00:00Z",
        updatedAt: "2026-07-01T11:05:00Z",
        primaryBadge: "updated_time",
        isActive: true,
      },
    ];
    mounted.update({ projection: secondProjection });

    const secondInput = host.querySelector<HTMLTextAreaElement>("[data-chat-composer-input]");
    expect(secondInput?.value).toBe("");
    secondInput!.value = "Draft for chat two";
    secondInput!.dispatchEvent(new Event("input", { bubbles: true }));

    mounted.update({ projection: fixtureProjection() });
    expect(host.querySelector<HTMLTextAreaElement>("[data-chat-composer-input]")?.value).toBe("Draft for chat one");

    mounted.update({ projection: secondProjection });
    expect(host.querySelector<HTMLTextAreaElement>("[data-chat-composer-input]")?.value).toBe("Draft for chat two");
  });

  test("submits composer text as approval guidance while approval is pending", () => {
    const host = document.createElement("section");
    const guidanceSubmissions: unknown[] = [];
    host.addEventListener("desktop-chat-approval-guidance-submit", (event) => {
      guidanceSubmissions.push((event as CustomEvent).detail);
    });
    const projection = fixtureProjection();
    projection.approvals = [{
      id: "approval-1",
      sessionKey: "websocket:chat-1",
      toolName: "workspace.write_file",
      status: "pending",
      prompt: "Allow writing notes.md?",
      choices: ["allow_once", "allow_session", "deny"],
    }];

    mountChatSurface(host, { projection });

    const input = host.querySelector<HTMLTextAreaElement>("[data-chat-composer-input]");
    input!.value = "Do not write files; summarize only.";
    host.querySelector<HTMLButtonElement>("[data-chat-composer-action='send']")?.click();

    expect(guidanceSubmissions).toEqual([{
      approvalId: "approval-1",
      guidance: "Do not write files; summarize only.",
    }]);
    expect(host.querySelector("[data-chat-region='queued-inputs']")).toBeNull();
  });

  test("queues composer text while the assistant turn is running and supports deleting it", () => {
    const host = document.createElement("section");
    const projection = fixtureProjection();
    projection.turns[1] = {
      ...projection.turns[1],
      process: {
        state: "running",
        summary: "Execution process · 2 tools",
        toolCount: 2,
      },
    };

    mountChatSurface(host, { projection });

    const input = host.querySelector<HTMLTextAreaElement>("[data-chat-composer-input]");
    input!.value = "Summarize after the tools finish.";
    host.querySelector<HTMLButtonElement>("[data-chat-composer-action='send']")?.click();

    const queue = host.querySelector("[data-chat-region='queued-inputs']");
    expect(queue?.textContent).toContain("Summarize after the tools finish.");
    expect(host.querySelector("[data-chat-composer-input]")?.textContent).toBe("");

    host.querySelector<HTMLButtonElement>("[data-queued-input-action='delete']")?.click();

    expect(host.querySelector("[data-chat-region='queued-inputs']")).toBeNull();
  });

  test("continues a paused queue by sending only the next queued input", () => {
    const host = document.createElement("section");
    const submissions: unknown[] = [];
    host.addEventListener("desktop-chat-message-submit", (event) => {
      submissions.push((event as CustomEvent).detail);
    });
    const projection = fixtureProjection();
    projection.queuedInputs = [
      {
        id: "queued-a",
        mode: "queued",
        content: "First paused message.",
        createdAt: "2026-07-01T10:20:00Z",
        status: "paused",
      },
      {
        id: "queued-b",
        mode: "queued",
        content: "Second paused message.",
        createdAt: "2026-07-01T10:21:00Z",
        status: "paused",
      },
    ];

    mountChatSurface(host, { projection });

    expect(host.querySelector("[data-chat-region='queued-inputs']")?.textContent).toContain("Queue paused");
    host.querySelector<HTMLButtonElement>("[data-queued-input-action='continue']")?.click();

    expect(submissions).toEqual([{ content: "First paused message." }]);
    expect(host.querySelector("[data-chat-region='queued-inputs']")?.textContent).not.toContain("First paused message.");
    expect(host.querySelector("[data-chat-region='queued-inputs']")?.textContent).toContain("Second paused message.");
  });

  test("renders resolved approvals as compact history results", () => {
    const host = document.createElement("section");
    const projection = fixtureProjection();
    projection.approvals = [{
      id: "approval-resolved",
      sessionKey: "websocket:chat-1",
      toolName: "workspace.read_file",
      status: "approved",
      prompt: "Allowed once",
      choices: ["allow_once", "allow_session", "deny"],
    }];

    mountChatSurface(host, { projection });

    const result = host.querySelector("[data-chat-region='approval-result']");
    expect(result?.textContent).toContain("Approved");
    expect(result?.textContent).toContain("workspace.read_file");
    expect(host.querySelector("[data-chat-region='approval-card']")).toBeNull();
  });
});

function fixtureProjection(): ChatUiProjection {
  return {
    activeSessionKey: "websocket:chat-1",
    sessions: [{
      key: "websocket:chat-1",
      chatId: "chat-1",
      title: "Investigate IAM certificate",
      createdAt: "2026-07-01T10:00:00Z",
      updatedAt: "2026-07-01T10:05:00Z",
      primaryBadge: "waiting_approval",
      isActive: true,
    }],
    turns: [
      {
        id: "m-user",
        role: "user",
        content: "Check the cert setup.",
        reasoningContent: "",
        timestamp: "2026-07-01T10:01:00Z",
        tools: [],
      },
      {
        id: "m-assistant",
        role: "assistant",
        content: "I found the relevant file.",
        reasoningContent: "Looking at workspace docs.",
        timestamp: "2026-07-01T10:02:00Z",
        process: {
          state: "waiting_approval",
          summary: "Execution process · 2 tools",
          toolCount: 2,
        },
        tools: [
          {
            id: "tool-1",
            name: "workspace.read_file",
            status: "completed",
            preview: "README contents",
            argsPreview: "{\"path\":\"README.md\"}",
            resultPreview: "README contents",
            detail: {
              argsText: "{\"path\":\"README.md\"}",
              responseText: "README contents",
              stdout: "",
              stderr: "",
            },
            kind: "result",
          },
          {
            id: "approval-1",
            name: "workspace.write_file",
            status: "waiting_approval",
            preview: "Needs approval",
            argsPreview: "{\"path\":\"notes.md\"}",
            resultPreview: "Needs approval",
            detail: {
              argsText: "{\"path\":\"notes.md\"}",
              responseText: "Needs approval",
              stdout: "",
              stderr: "",
            },
            kind: "result",
            approvalId: "approval-1",
          },
        ],
      },
    ],
    approvals: [],
    liveSubagents: [],
    queuedInputs: [],
    detailPanel: {
      kind: "none",
      open: false,
      presentation: "drawer",
    },
    branchSource: {
      canBranchSession: true,
      portableContextKeys: ["chatId", "sessionKey"],
      runtimeStateExcluded: true,
    },
  };
}
