export const DEFAULT_AGENT_MODEL = "deepseek-reasoner";
export const DEFAULT_AGENT_MAX_TOKENS = 8192;
export const DEFAULT_AGENT_CONTEXT_WINDOW_TOKENS = 65536;
export const DEFAULT_AGENT_TEMPERATURE = 0.1;
export const DEFAULT_AGENT_MAX_TOOL_ITERATIONS = 200;
export const DEFAULT_AGENT_MAX_TOOL_RESULT_CHARS = 16000;
